### ISSUE TITLE
Can not start the server

### ISSUE THREAD

**Issue by jengweneg** [france-connect/service-providers-examples#4]
Hello,

I can't start the nodejs web server when i do "PORT=3052 npm start"

I get this error
Hop e you can help

> dataProvider1@0.0.0 start /root/data-providers-examples/dataProvider1
> ./bin/www

/root/data-providers-examples/dataProvider1/helpers/configManager.js:28
    var data = _.map(this._rawConfig.mongo.hosts, function(host){
                                          ^
TypeError: Cannot read property 'hosts' of undefined
    at Configuration.getReplicationHosts (/root/data-providers-examples/dataProvider1/helpers/configManager.js:28:43)
    at Object.<anonymous> (/root/data-providers-examples/dataProvider1/services/dao.js:5:32)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/data-providers-examples/dataProvider1/services/dataService.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/data-providers-examples/dataProvider1/routes/index.js:3:24)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

npm ERR! Linux 3.10.23-xxxx-std-ipv6-32
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! dataProvider1@0.0.0 start: `./bin/www`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the dataProvider1@0.0.0 start script './bin/www'.
npm ERR! This is most likely a problem with the dataProvider1 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs dataProvider1
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls dataProvider1
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/data-providers-examples/dataProvider1/npm-debug.log

**Comment by hoshin** [comment]
Hello @jengweneg, and sorry for the late reply.

I'm not involved in the project anymore so my info might be a bit outdated, but if I were you I'd double check I've written the configuration file (`./config/config.json`), and that it has a "mongo" section with relevant data (port & host) to connect to a mongodb instance. We deliberately left out the mongo section to force people to take the time to set their own up, but it could've gone with a more explicit error message :-/

adding a section in your configuration like the one below should help : 

```
{
...
mongo:{
    host:<your mongo host>,
    port:<your mongo port>
}
```
}
Maybe you can even leave out the port if you're using the standard one.

Hope this helps.

Martin
